root: false
cache: pip

language: python

python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"

stages:
  - test

jobs:
  include:
    # test stage
    - stage: test
      env: TOXENV=py

script:
  - tox
